apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-plan-service
spec:
  selector:
    matchLabels:
      app: onboarding-plan-service
  replicas: 2
  template:
    metadata:
      labels:
        app: onboarding-plan-service
    spec:
      containers:
      - name: onboarding-plan-service
        image: modern-app/onboarding-plan-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
          - name: mongo_user
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: mongo_pwd
            valueFrom:
              secretKeyRef:
                key: password
                name: mongo-creds
---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-plan-service
spec:
  selector:
    app: onboarding-plan-service
  ports:
  - port: 8082
    targetPort: 8080
  type: LoadBalancer

